version: '3.5'

services:
  redis:
    image: redis
    networks:
      - backend
    restart: always
  chatto:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chatto/:/code/
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - chatto
      - backend
    depends_on:
      - redis
    restart: always
networks:
  chatto:
    name: chatto
  backend:
