version: '3.5'
services:
  mongodb:
    image: mongo
    volumes:
      - ./data/runtime/db:/data/db
      - ./data/dump:/dump
    command: mongod --smallfiles
    networks:
      - rocketchat
    ports:
      - 27017:27017
  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      - Accounts_UseDNSDomainCheck=True
    networks:
      - chatto
      - rocketchat
    ports:
      - 3000:3000
    depends_on:
      - mongodb
#  hubot:
#    image: rocketchat/hubot-rocketchat:latest
#    environment:
#      - ROCKETCHAT_URL=192.168.234.131:3000
#      - ROCKETCHAT_ROOM=GENERAL
#      - ROCKETCHAT_USER=Botname
#      - ROCKETCHAT_PASSWORD=BotPassw0rd
#      - BOT_NAME=Botname
#      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
#    links:
#      - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
#  ports:
#    - 3001:8080
networks:
    chatto:
      external: true
      name: chatto
    rocketchat:

             
